### ISSUE TITLE
Getting strict MIME type error

### ISSUE THREAD

**Issue by andrejarh** [reduxframework/extension-boilerplate#4]
Here is the error: 

Refused to execute script from 'http://localhost:8888/wordpress/wp-admin/admin-ajax.php?action=red…wp-admin%2Fadmin-ajax.php%3Faction%3Dredux_p%26nonce%3D89f2dc949b%26url%3D' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by kprovance** [comment]
Not sure why you are posting this here.  Anyways, our ad server is down, and that's why the message.  We hope to have it up again shortly.
